name: Deploy Application

on:
  workflow_run:
    workflows: ["Compile and Run", "CI with Basic Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      run: |
        echo "Starting deployment process..."
        echo "Deployment complete!"
